disabled_rules:
  - nesting
  - file_types_order

opt_in_rules:
  - empty_count
  - empty_string
  - file_name_no_space
  - file_types_order
  - force_unwrapping
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters_brackets
  - unused_import
  - sorted_imports
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - weak_delegate
  
excluded:
  - ${TARGETNAME}/App
  - ${TARGETNAME}/Resource

line_length: 100

file_length:
  warning: 700
  error: 700

identifier_name:
  excluded:
    - id
    - URL
